"""Centralized prompt templates for the Planner."""

SYSTEM_PROMPT = """You are a helpful infrastructure planning assistant. Your role is to look at what a \
repository needs and translate that into a well-structured infrastructure model as JSON.

Think of yourself as a senior DevOps engineer pairing with a developer — you understand their stack, \
anticipate what services they'll need, and lay out a clean, practical infrastructure plan.

The InfraModel schema has these top-level sections:
- **version**, **project_name**, **routing**, **capabilities**, **services**, **cluster_assumptions** \
  — the core contract. Always populate these.
- **helm** — Helm chart generation. Off by default (`enabled: false`). Only turn it on when the user \
  explicitly asks for Helm packaging.
- **iac** — Terraform cluster provisioning for AWS EKS, GCP GKE, or Azure AKS. Off by default. \
  Only enable when the user asks for cloud infrastructure or the hints mention a specific provider.
- **cicd** — CI/CD pipeline generation. Defaults to GitHub Actions only. Add other providers \
  (gitlab_ci, bitbucket_pipelines, circleci) only when the user requests them.
- **monitoring** — Prometheus ServiceMonitors, Grafana dashboards, and alerting rules. Off by default. \
  Enable when the user asks for observability or monitoring.
- **multi_tenancy** — Namespace-isolated tenants with ResourceQuotas and NetworkPolicies. Off by default. \
  Enable only when the user explicitly needs tenant isolation.

Your guiding principle is **conservative defaults**: start with just the core stack (compose, K8s, \
GitHub Actions CI) and only activate enterprise features when there's a clear signal from the user's \
hints or the repository analysis. When in doubt, leave a feature disabled — the user can always \
enable it in a follow-up pass.

When you respond, just provide the JSON that matches the InfraModel schema. \
No need for explanations or markdown wrapping — the JSON itself is your answer.
"""

PLAN_PROMPT = """Here's a repository that needs infrastructure planning. Take a look at what the \
analyzer found and the user's preferences, then produce an InfraModel JSON for it.

## What the analyzer found
{analyzer_output}

## What the user wants
{hints}

## The InfraModel schema to follow
{schema}

## A few things to keep in mind

- Each inferred service (like postgres, redis, a worker queue) should appear as its own service entry \
so that compose and k8s manifests can be generated for it.
- Sometimes dependencies are implicit — for example, Celery needs a broker, so if Redis isn't already \
in the dependency list, it makes sense to add a Redis service and wire it via depends_on.
- If the user mentions GPU needs, reflect that in capabilities.needs_gpu.
- Heavier workloads (video processing, streaming) generally benefit from more generous memory_limits.
- When no scale preference is given, "dev" is a safe default — minimal replicas, reasonable resource requests.
- Official images work well for infrastructure services: postgres:16, redis:7-alpine, mongo:7, etc.
- Standard ports are what people expect: postgres on 5432, redis on 6379, mongodb on 27017.
- Services typically need environment variables to talk to each other — a DATABASE_URL for the app to \
reach postgres, a REDIS_URL for cache connections, and so on.
- The project_name usually comes from the repository directory name.
- For dev scale, "localhost" is a natural routing domain.

### Extended capabilities

The model also supports several optional sections — only enable the ones the user explicitly asks for \
or that the hints suggest:

- **Helm charts** (`helm`): If the user wants Helm, set `helm.enabled: true` and optionally \
provide a `chart_name`. The generator will produce a full Helm chart directory.
- **Cluster provisioning** (`iac`): If the user wants Terraform for EKS/GKE/AKS, set `iac.enabled: true` \
and pick the right `cloud_provider` and `region`. This generates Terraform files to spin up a managed K8s cluster.
- **Multi-CI/CD** (`cicd`): By default only GitHub Actions is generated, but the user can request \
GitLab CI, Bitbucket Pipelines, or CircleCI by listing them in `cicd.providers`.
- **Monitoring** (`monitoring`): If the user wants observability, set `monitoring.enabled: true`. \
This generates Prometheus ServiceMonitors, Grafana dashboards, and alerting rules. \
Sensible alert thresholds are provided by default but can be customized.
- **Multi-tenancy** (`multi_tenancy`): If the user wants namespace-isolated tenants, set \
`multi_tenancy.enabled: true` and define tenants with resource quotas. NetworkPolicies are \
generated by default for inter-tenant isolation.

If the user hasn't mentioned any of these, just leave them at their defaults (disabled).

Here's a small example of what good output looks like for a Python/FastAPI app with postgres:

```
{{
  "version": "1.0",
  "project_name": "my-app",
  "routing": {{ "domain": "localhost", "ingress_controller": "nginx" }},
  "capabilities": {{ "needs_gpu": false, "latency_sensitive": false, "multi_tenant": false }},
  "services": [
    {{
      "name": "web",
      "type": "app",
      "image": "python:3.11-slim",
      "entrypoint": "uvicorn main:app --host 0.0.0.0 --port 8000",
      "ports": [{{ "container": 8000, "host": 8000, "protocol": "TCP" }}],
      "depends_on": ["postgres"],
      "env": {{
        "DATABASE_URL": {{ "kind": "literal", "value": "postgres://user:pass@postgres:5432/db" }}
      }},
      "sizing": {{ "scale": "dev", "replicas": 1, "cpu_requests": "100m", "cpu_limits": "500m", "memory_requests": "256Mi", "memory_limits": "512Mi", "workload_type": "api" }},
      "volumes": []
    }},
    {{
      "name": "postgres",
      "type": "database",
      "image": "postgres:16-alpine",
      "ports": [{{ "container": 5432, "host": 5432, "protocol": "TCP" }}],
      "depends_on": [],
      "env": {{ "POSTGRES_PASSWORD": {{ "kind": "secret", "ref": "POSTGRES_PASSWORD" }} }},
      "sizing": {{ "scale": "dev", "replicas": 1, "cpu_requests": "100m", "cpu_limits": "500m", "memory_requests": "256Mi", "memory_limits": "512Mi", "workload_type": "api" }},
      "volumes": [{{ "name": "pgdata", "mount_path": "/var/lib/postgresql/data" }}]
    }}
  ],
  "cluster_assumptions": {{ "ingress_controller": "nginx", "ingress_class_name": "nginx", "tls_enabled": true, "cert_manager": true, "storage_class": "standard" }},
  "helm": {{ "enabled": false }},
  "iac": {{ "enabled": false }},
  "cicd": {{ "providers": ["github_actions"], "registry": "ghcr.io", "cluster_auth": "kubeconfig", "run_tests": true, "lint": true, "auto_deploy": true }},
  "monitoring": {{ "enabled": false }},
  "multi_tenancy": {{ "enabled": false }}
}}
```

Now, based on the repository analysis and user hints above, produce the InfraModel JSON.
"""

REPAIR_PROMPT = """The JSON from the previous attempt didn't quite pass schema validation. Here's what went wrong:

{validation_error}

For reference, here's what was originally asked:
{original_prompt}

A few common pitfalls to watch for:
- **services** must be a non-empty list; each needs name, type, and image at minimum.
- **cicd.providers** only accepts: "github_actions", "gitlab_ci", "bitbucket_pipelines", "circleci".
- **iac.cloud_provider** only accepts: "aws", "gcp", "azure".  **iac.tool** must be "terraform".
- **monitoring.metrics_port** must be between 1 and 65535.
- **multi_tenancy.isolation_level** only accepts: "namespace".  Each tenant needs a non-empty name.
- **helm**, **iac**, **monitoring**, and **multi_tenancy** all default to disabled — only include \
them if the original request asked for them, and make sure `enabled: true` is set when you do.
- Env vars need a "kind" discriminator: "literal" (with "value"), "ref" (with "ref"), or "secret" (with "ref").

Could you adjust the JSON so it passes validation? Just the corrected JSON is great.
"""

PLAN_SUMMARY_TEMPLATE = """# Infrastructure Plan

## Project: {project_name}

### Services Detected
{services_summary}

### Configuration
- **Scale Profile:** {scale}
- **Ingress Controller:** {ingress_controller}
- **TLS Enabled:** {tls_enabled}

### CI/CD
- **Providers:** {cicd_providers}
- **Registry:** {cicd_registry}
- **Auto Deploy:** {cicd_auto_deploy}

### Enterprise Features
- **Helm Charts:** {helm_status}
- **IaC / Terraform:** {iac_status}
- **Monitoring:** {monitoring_status}
- **Multi-Tenancy:** {tenancy_status}

### Environment Variables
{env_summary}

### Suggestions
{suggestions}
"""
